2019-08-01 12:14:00,015  __init__/__init__.py:73  _________visit start_________2019-08-01 12:14:00
2019-08-01 12:14:04,154  __init__/__init__.py:73  ip不可用：http://117.90.1.143:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27A30>, 'Connection to 117.90.1.143 timed out. (connect timeout=2)'))
2019-08-01 12:14:07,185  __init__/__init__.py:73  ip不可用：http://101.200.43.49:6000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435B030>, 'Connection to 101.200.43.49 timed out. (connect timeout=2)'))
2019-08-01 12:14:10,215  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435B2D0>, 'Connection to 58.22.222.88 timed out. (connect timeout=2)'))
2019-08-01 12:14:13,246  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27F10>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
2019-08-01 12:14:16,276  __init__/__init__.py:73  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27870>, 'Connection to 203.110.164.139 timed out. (connect timeout=2)'))
2019-08-01 12:14:18,417  __init__/__init__.py:73  ip不可用：http://117.90.1.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0435B3D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:14:21,447  __init__/__init__.py:73  ip不可用：http://117.90.2.35:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435B710>, 'Connection to 117.90.2.35 timed out. (connect timeout=2)'))
2019-08-01 12:14:24,477  __init__/__init__.py:73  ip不可用：http://121.232.148.191:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435BB50>, 'Connection to 121.232.148.191 timed out. (connect timeout=2)'))
2019-08-01 12:14:27,508  __init__/__init__.py:73  ip不可用：http://175.44.148.100:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043690D0>, 'Connection to 175.44.148.100 timed out. (connect timeout=2)'))
2019-08-01 12:14:30,539  __init__/__init__.py:73  ip不可用：http://180.118.135.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369630>, 'Connection to 180.118.135.47 timed out. (connect timeout=2)'))
2019-08-01 12:14:32,694  __init__/__init__.py:73  ip不可用：http://117.90.1.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:14:35,725  __init__/__init__.py:73  ip不可用：http://14.29.232.142:8082HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043695B0>, 'Connection to 14.29.232.142 timed out. (connect timeout=2)'))
2019-08-01 12:14:37,771  __init__/__init__.py:73  ip不可用：http://36.111.146.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x043696F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:14:39,911  __init__/__init__.py:73  ip不可用：http://117.90.1.201:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04369B30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:14:42,942  __init__/__init__.py:73  ip不可用：http://60.188.38.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043700B0>, 'Connection to 60.188.38.186 timed out. (connect timeout=2)'))
2019-08-01 12:14:43,957  __init__/__init__.py:73  _________visit end_________
2019-08-01 12:14:43
2019-08-01 12:15:00,016  __init__/__init__.py:73  _________visit start_________2019-08-01 12:15:00
2019-08-01 12:15:04,093  __init__/__init__.py:73  ip不可用：http://117.90.1.143:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04370C70>, 'Connection to 117.90.1.143 timed out. (connect timeout=2)'))
2019-08-01 12:15:07,124  __init__/__init__.py:73  ip不可用：http://101.200.43.49:6000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27550>, 'Connection to 101.200.43.49 timed out. (connect timeout=2)'))
2019-08-01 12:15:10,154  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27B70>, 'Connection to 58.22.222.88 timed out. (connect timeout=2)'))
2019-08-01 12:15:13,185  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369FB0>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
2019-08-01 12:15:16,215  __init__/__init__.py:73  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043699D0>, 'Connection to 203.110.164.139 timed out. (connect timeout=2)'))
2019-08-01 12:15:18,387  __init__/__init__.py:73  ip不可用：http://117.90.1.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x043697F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:15:21,417  __init__/__init__.py:73  ip不可用：http://117.90.2.35:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369350>, 'Connection to 117.90.2.35 timed out. (connect timeout=2)'))
2019-08-01 12:15:24,448  __init__/__init__.py:73  ip不可用：http://121.232.148.191:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04370D10>, 'Connection to 121.232.148.191 timed out. (connect timeout=2)'))
2019-08-01 12:15:27,478  __init__/__init__.py:73  ip不可用：http://175.44.148.100:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369470>, 'Connection to 175.44.148.100 timed out. (connect timeout=2)'))
2019-08-01 12:15:30,509  __init__/__init__.py:73  ip不可用：http://180.118.135.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369330>, 'Connection to 180.118.135.47 timed out. (connect timeout=2)'))
2019-08-01 12:15:32,649  __init__/__init__.py:73  ip不可用：http://117.90.1.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04369810>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:15:35,680  __init__/__init__.py:73  ip不可用：http://14.29.232.142:8082HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369D90>, 'Connection to 14.29.232.142 timed out. (connect timeout=2)'))
2019-08-01 12:15:37,726  __init__/__init__.py:73  ip不可用：http://36.111.146.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04370BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:15:39,835  __init__/__init__.py:73  ip不可用：http://117.90.1.201:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27950>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 12:15:42,881  __init__/__init__.py:73  ip不可用：http://60.188.38.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03E27A50>, 'Connection to 60.188.38.186 timed out. (connect timeout=2)'))
2019-08-01 12:15:43,896  __init__/__init__.py:73  _________visit end_________
2019-08-01 12:15:43
2019-08-01 12:16:00,002  __init__/__init__.py:73  _________visit start_________2019-08-01 12:16:00
2019-08-01 12:16:04,095  __init__/__init__.py:73  ip不可用：http://117.90.1.143:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043702D0>, 'Connection to 117.90.1.143 timed out. (connect timeout=2)'))
2019-08-01 12:16:07,125  __init__/__init__.py:73  ip不可用：http://101.200.43.49:6000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04370430>, 'Connection to 101.200.43.49 timed out. (connect timeout=2)'))
2019-08-01 12:16:10,156  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04370A30>, 'Connection to 58.22.222.88 timed out. (connect timeout=2)'))
2019-08-01 12:16:13,186  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369030>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
2019-08-01 12:16:16,217  __init__/__init__.py:73  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04369470>, 'Connection to 203.110.164.139 timed out. (connect timeout=2)'))
